name: Tests/Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:


env:
  REGISRTY: ghcr.io
  IMAGE_NAME: metramak/atis_ulll

jobs:
  test:
    runs-on: ubuntu-ubuntu
    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: pip install -r requirements.txt pytest

    - name: Run Tests
      run: pytest tests/ -v
